/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCravoLandingRouteImport } from './routes/api.public.cravo.landing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCravoLandingRoute = ApiPublicCravoLandingRouteImport.update({
  id: '/api/public/cravo/landing',
  path: '/api/public/cravo/landing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cravo/landing': typeof ApiPublicCravoLandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cravo/landing': typeof ApiPublicCravoLandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cravo/landing': typeof ApiPublicCravoLandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/cravo/landing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cravo/landing'
  id: '__root__' | '/' | '/api/public/cravo/landing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCravoLandingRoute: typeof ApiPublicCravoLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cravo/landing': {
      id: '/api/public/cravo/landing'
      path: '/api/public/cravo/landing'
      fullPath: '/api/public/cravo/landing'
      preLoaderRoute: typeof ApiPublicCravoLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCravoLandingRoute: ApiPublicCravoLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
