/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as CravoRouteImport } from './routes/cravo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCravoTesteRouteImport } from './routes/api.public.cravo.teste'
import { Route as ApiPublicCravoManifestRouteImport } from './routes/api.public.cravo.manifest'
import { Route as ApiPublicCravoLandingRouteImport } from './routes/api.public.cravo.landing'
import { Route as ApiPublicCravoExperienciaRouteImport } from './routes/api.public.cravo.experiencia'
import { Route as ApiPublicCravoAssetsSplatRouteImport } from './routes/api.public.cravo.assets.$'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CravoRoute = CravoRouteImport.update({
  id: '/cravo',
  path: '/cravo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCravoTesteRoute = ApiPublicCravoTesteRouteImport.update({
  id: '/api/public/cravo/teste',
  path: '/api/public/cravo/teste',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCravoManifestRoute = ApiPublicCravoManifestRouteImport.update({
  id: '/api/public/cravo/manifest',
  path: '/api/public/cravo/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCravoLandingRoute = ApiPublicCravoLandingRouteImport.update({
  id: '/api/public/cravo/landing',
  path: '/api/public/cravo/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCravoExperienciaRoute =
  ApiPublicCravoExperienciaRouteImport.update({
    id: '/api/public/cravo/experiencia',
    path: '/api/public/cravo/experiencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCravoAssetsSplatRoute =
  ApiPublicCravoAssetsSplatRouteImport.update({
    id: '/api/public/cravo/assets/$',
    path: '/api/public/cravo/assets/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cravo': typeof CravoRoute
  '/map': typeof MapRoute
  '/api/public/cravo/experiencia': typeof ApiPublicCravoExperienciaRoute
  '/api/public/cravo/landing': typeof ApiPublicCravoLandingRoute
  '/api/public/cravo/manifest': typeof ApiPublicCravoManifestRoute
  '/api/public/cravo/teste': typeof ApiPublicCravoTesteRoute
  '/api/public/cravo/assets/$': typeof ApiPublicCravoAssetsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cravo': typeof CravoRoute
  '/map': typeof MapRoute
  '/api/public/cravo/experiencia': typeof ApiPublicCravoExperienciaRoute
  '/api/public/cravo/landing': typeof ApiPublicCravoLandingRoute
  '/api/public/cravo/manifest': typeof ApiPublicCravoManifestRoute
  '/api/public/cravo/teste': typeof ApiPublicCravoTesteRoute
  '/api/public/cravo/assets/$': typeof ApiPublicCravoAssetsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cravo': typeof CravoRoute
  '/map': typeof MapRoute
  '/api/public/cravo/experiencia': typeof ApiPublicCravoExperienciaRoute
  '/api/public/cravo/landing': typeof ApiPublicCravoLandingRoute
  '/api/public/cravo/manifest': typeof ApiPublicCravoManifestRoute
  '/api/public/cravo/teste': typeof ApiPublicCravoTesteRoute
  '/api/public/cravo/assets/$': typeof ApiPublicCravoAssetsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cravo'
    | '/map'
    | '/api/public/cravo/experiencia'
    | '/api/public/cravo/landing'
    | '/api/public/cravo/manifest'
    | '/api/public/cravo/teste'
    | '/api/public/cravo/assets/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cravo'
    | '/map'
    | '/api/public/cravo/experiencia'
    | '/api/public/cravo/landing'
    | '/api/public/cravo/manifest'
    | '/api/public/cravo/teste'
    | '/api/public/cravo/assets/$'
  id:
    | '__root__'
    | '/'
    | '/cravo'
    | '/map'
    | '/api/public/cravo/experiencia'
    | '/api/public/cravo/landing'
    | '/api/public/cravo/manifest'
    | '/api/public/cravo/teste'
    | '/api/public/cravo/assets/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CravoRoute: typeof CravoRoute
  MapRoute: typeof MapRoute
  ApiPublicCravoExperienciaRoute: typeof ApiPublicCravoExperienciaRoute
  ApiPublicCravoLandingRoute: typeof ApiPublicCravoLandingRoute
  ApiPublicCravoManifestRoute: typeof ApiPublicCravoManifestRoute
  ApiPublicCravoTesteRoute: typeof ApiPublicCravoTesteRoute
  ApiPublicCravoAssetsSplatRoute: typeof ApiPublicCravoAssetsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cravo': {
      id: '/cravo'
      path: '/cravo'
      fullPath: '/cravo'
      preLoaderRoute: typeof CravoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cravo/teste': {
      id: '/api/public/cravo/teste'
      path: '/api/public/cravo/teste'
      fullPath: '/api/public/cravo/teste'
      preLoaderRoute: typeof ApiPublicCravoTesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cravo/manifest': {
      id: '/api/public/cravo/manifest'
      path: '/api/public/cravo/manifest'
      fullPath: '/api/public/cravo/manifest'
      preLoaderRoute: typeof ApiPublicCravoManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cravo/landing': {
      id: '/api/public/cravo/landing'
      path: '/api/public/cravo/landing'
      fullPath: '/api/public/cravo/landing'
      preLoaderRoute: typeof ApiPublicCravoLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cravo/experiencia': {
      id: '/api/public/cravo/experiencia'
      path: '/api/public/cravo/experiencia'
      fullPath: '/api/public/cravo/experiencia'
      preLoaderRoute: typeof ApiPublicCravoExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cravo/assets/$': {
      id: '/api/public/cravo/assets/$'
      path: '/api/public/cravo/assets/$'
      fullPath: '/api/public/cravo/assets/$'
      preLoaderRoute: typeof ApiPublicCravoAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CravoRoute: CravoRoute,
  MapRoute: MapRoute,
  ApiPublicCravoExperienciaRoute: ApiPublicCravoExperienciaRoute,
  ApiPublicCravoLandingRoute: ApiPublicCravoLandingRoute,
  ApiPublicCravoManifestRoute: ApiPublicCravoManifestRoute,
  ApiPublicCravoTesteRoute: ApiPublicCravoTesteRoute,
  ApiPublicCravoAssetsSplatRoute: ApiPublicCravoAssetsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
